config/routes.rb
Rails.application.routes.draw do
  resources :applications


  get 'applicationform/index'

  get 'welcome/index'
  get 'application/list'
  get 'application/new'
  post 'application/create'

  post "grader_application/new" => 'grader_application#create'
  get 'grader_application/show'

  patch 'application/update'
  get 'application/show'
  get 'application/edit'
  get 'application/delete'
  get 'application/update'
  get 'application/show_student_application'
  get 'application/index'
  get 'applicationform/index'
  post '/grader_application/list'
  post '/grader_application/accept' => 'grader_application#accept'
  post '/grader_application/reject' => 'grader_application#reject'
  get '/courses' => 'courses#scrape'
  put 'grader_application/:id' => 'grader_application#accept'
  put 'grader_application/:id' => 'grader_application#reject'


  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :recommandationform
  resources :courses
  resources :applicationform
  get 'grader_application/list'
  resources :grader_application

  root 'welcome#index'
  post "recommandationform/new" => 'recommandationform#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<%= stylesheet_link_tag "header" %>

<nav>
    <span><%= link_to "Home", root_path %></span>
<% if user_signed_in? %>
    <% if current_user.is_teacher %>
    	<span><a href="/grader_application/list">Student Application Portal</a></span>
    <% else %>
			<span><a href="/grader_application">Grader Applications</a></span>
        <span><%= link_to "Courses", courses_url %></span>
    <% end %>
    <span><%= link_to 'Logout', destroy_user_session_path, method: :delete %></span>
<% else %>
    <span><%= link_to 'Login', new_user_session_path %></span>
<% end %>
</nav>